//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDP_Project_WindowForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class attraction_order
    {
        public attraction_order()
        {
            this.order = new HashSet<order>();
        }
    
        public string AttractionOrderID { get; set; }
        public string AttractionName { get; set; }
        public int AdultNum { get; set; }
        public int ChildNum { get; set; }
        public decimal AdultPrice { get; set; }
        public decimal ChildPrice { get; set; }
    
        public virtual attraction attraction { get; set; }
        public virtual ICollection<order> order { get; set; }
    }
}
