//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDP_Project_WindowForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class corganizer
    {
        public corganizer()
        {
            this.cruise = new HashSet<cruise>();
        }
    
        public string OrganID { get; set; }
        public string OrganizerE { get; set; }
        public string OrganizerC { get; set; }
    
        public virtual ICollection<cruise> cruise { get; set; }
    }
}
