//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDP_Project_WindowForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer
    {
        public customer()
        {
            this.feedback = new HashSet<feedback>();
            this.order = new HashSet<order>();
        }
    
        public string CustID { get; set; }
        public string Surname { get; set; }
        public string GivenName { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string Gender { get; set; }
        public string Passport { get; set; }
        public string Contact { get; set; }
        public string Nationality { get; set; }
    
        public virtual ICollection<feedback> feedback { get; set; }
        public virtual ICollection<order> order { get; set; }
    }
}
