//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDP_Project_WindowForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class equipmentlist
    {
        public string VehicleBookingID { get; set; }
        public string EquipID { get; set; }
        public Nullable<decimal> EquipBookPrice { get; set; }
    
        public virtual equipment equipment { get; set; }
        public virtual vehiclebooking vehiclebooking { get; set; }
    }
}
