//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDP_Project_WindowForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class flightclass
    {
        public flightclass()
        {
            this.flight_booking = new HashSet<flight_booking>();
        }
    
        public string flightclass_id { get; set; }
        public string FlightNo { get; set; }
        public string Class { get; set; }
        public decimal Price_Adult { get; set; }
        public decimal Price_Children { get; set; }
        public decimal Price_Infant { get; set; }
        public decimal Tax { get; set; }
    
        public virtual ICollection<flight_booking> flight_booking { get; set; }
    }
}
