//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDP_Project_WindowForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class indirect
    {
        public string FlightNo { get; set; }
        public int StopNo { get; set; }
        public string Stop { get; set; }
        public System.DateTime DateTime { get; set; }
    }
}
