//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDP_Project_WindowForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class vehicle
    {
        public vehicle()
        {
            this.vehiclebooking = new HashSet<vehiclebooking>();
        }
    
        public string VehicleID { get; set; }
        public string VehicleName { get; set; }
        public decimal Price { get; set; }
        public string VehicleType { get; set; }
        public int Capacity { get; set; }
        public string Gear { get; set; }
        public string Color { get; set; }
        public string Photo { get; set; }
    
        public virtual ICollection<vehiclebooking> vehiclebooking { get; set; }
    }
}
