//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDP_Project_WindowForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class cruise_order
    {
        public cruise_order()
        {
            this.order = new HashSet<order>();
        }
    
        public string CruiseOrderID { get; set; }
        public string CruiseID { get; set; }
        public decimal Price { get; set; }
        public int CustNum { get; set; }
    
        public virtual cruise cruise { get; set; }
        public virtual ICollection<order> order { get; set; }
    }
}
