//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDP_Project_WindowForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class hotel_room
    {
        public hotel_room()
        {
            this.hotelbooking = new HashSet<hotelbooking>();
        }
    
        public string HotelRoomID { get; set; }
        public string HotelID { get; set; }
        public string Hotel_chi_name { get; set; }
        public string Hotel_room_name { get; set; }
        public string Hotel__room_size { get; set; }
        public int max_audults { get; set; }
        public int max_child { get; set; }
        public string Hotel_room_description { get; set; }
        public decimal Fare { get; set; }
    
        public virtual hotel hotel { get; set; }
        public virtual ICollection<hotelbooking> hotelbooking { get; set; }
    }
}
