//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDP_Project_WindowForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class vehiclebooking
    {
        public vehiclebooking()
        {
            this.equipmentlist = new HashSet<equipmentlist>();
            this.order = new HashSet<order>();
        }
    
        public string VehicleOrderID { get; set; }
        public string VehicleID { get; set; }
        public System.DateTime PickupDate { get; set; }
        public System.DateTime DropoffDate { get; set; }
        public decimal VehicleBookPrice { get; set; }
    
        public virtual ICollection<equipmentlist> equipmentlist { get; set; }
        public virtual ICollection<order> order { get; set; }
        public virtual vehicle vehicle { get; set; }
    }
}
