//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDP_Project_WindowForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class cruise
    {
        public cruise()
        {
            this.cruise_order = new HashSet<cruise_order>();
        }
    
        public string CruiseID { get; set; }
        public string CruiseName { get; set; }
        public decimal RefPrice { get; set; }
        public int TourDay { get; set; }
        public string OrganID { get; set; }
        public string Info { get; set; }
        public System.DateTime StartDate { get; set; }
    
        public virtual corganizer corganizer { get; set; }
        public virtual ICollection<cruise_order> cruise_order { get; set; }
    }
}
