//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDP_Project_WindowForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class flight_booking
    {
        public flight_booking()
        {
            this.order = new HashSet<order>();
        }
    
        public string FlightOrderID { get; set; }
        public string FlightID { get; set; }
        public string FlightClassID { get; set; }
        public decimal AdultPrice { get; set; }
        public decimal ChildPrice { get; set; }
        public decimal InfantPrice { get; set; }
        public int AdultNum { get; set; }
        public int ChildNum { get; set; }
        public int InfantNum { get; set; }
        public decimal totalPrice { get; set; }
        public string idReturn { get; set; }
    
        public virtual flightclass flightclass { get; set; }
        public virtual flightschedule flightschedule { get; set; }
        public virtual ICollection<order> order { get; set; }
    }
}
