//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDP_Project_WindowForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class hotel
    {
        public hotel()
        {
            this.hotel_room = new HashSet<hotel_room>();
        }
    
        public string HotelID { get; set; }
        public string Hotel_chi_name { get; set; }
        public string Hotel_en_name { get; set; }
        public decimal Star { get; set; }
        public decimal Rating { get; set; }
        public string Region { get; set; }
        public string address { get; set; }
        public string tel { get; set; }
        public string dest { get; set; }
    
        public virtual ICollection<hotel_room> hotel_room { get; set; }
    }
}
