//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDP_Project_WindowForm
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class sdp_datebaseEntities : DbContext
    {
        public sdp_datebaseEntities()
            : base("name=sdp_datebaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<attract_price> attract_price { get; set; }
        public DbSet<attraction> attraction { get; set; }
        public DbSet<attraction_order> attraction_order { get; set; }
        public DbSet<carrier> carrier { get; set; }
        public DbSet<corganizer> corganizer { get; set; }
        public DbSet<cruise> cruise { get; set; }
        public DbSet<cruise_order> cruise_order { get; set; }
        public DbSet<customer> customer { get; set; }
        public DbSet<driver_roster> driver_roster { get; set; }
        public DbSet<equipment> equipment { get; set; }
        public DbSet<equipmentlist> equipmentlist { get; set; }
        public DbSet<feedback> feedback { get; set; }
        public DbSet<flight_booking> flight_booking { get; set; }
        public DbSet<flightclass> flightclass { get; set; }
        public DbSet<flightschedule> flightschedule { get; set; }
        public DbSet<hotel> hotel { get; set; }
        public DbSet<hotel_room> hotel_room { get; set; }
        public DbSet<hotelbooking> hotelbooking { get; set; }
        public DbSet<indirect> indirect { get; set; }
        public DbSet<order> order { get; set; }
        public DbSet<staff> staff { get; set; }
        public DbSet<vehicle> vehicle { get; set; }
        public DbSet<vehiclebooking> vehiclebooking { get; set; }
    }
}
