//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDP_Project_WindowForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public string OrderID { get; set; }
        public string CustID { get; set; }
        public string StaffID { get; set; }
        public System.DateTime OrderDate { get; set; }
        public string FlightOrderID { get; set; }
        public string HotelOrderID { get; set; }
        public string AttractionOrderID { get; set; }
        public string CruiseOrderID { get; set; }
        public string TransportOrderID { get; set; }
        public string isTemp { get; set; }
    
        public virtual attraction_order attraction_order { get; set; }
        public virtual cruise_order cruise_order { get; set; }
        public virtual customer customer { get; set; }
        public virtual flight_booking flight_booking { get; set; }
        public virtual hotelbooking hotelbooking { get; set; }
        public virtual staff staff { get; set; }
        public virtual vehiclebooking vehiclebooking { get; set; }
    }
}
